services:
  db:
    container_name: db
    image: postgres:14
    hostname: db
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data:delegated
    restart: always
    networks:
      default:
        aliases:
          - 'db.sandbox'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=secrect
      - POSTGRES_USER=postgres

  turbo:
    container_name: api
    hostname: api
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./:/app/
      - ./node_modules:/app/node_modules
        # Just specify a path and let the Engine create a volume
      # - /app/node_modules/
    networks:
      default:
        aliases:
          - 'api.sandbox'
    restart: always

networks:
  turbo-network:
    driver: bridge
volumes:
  db_data:
